apiVersion: skaffold/v2beta26
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: neddy10/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        cacheFrom:
          - neddy10/auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: neddy10/client
      context: client
      docker:
        dockerfile: Dockerfile
        cacheFrom:
          - neddy10/client
      sync:
        manual:
          - src: '**/*.js'
            dest: .
